version: "3.9"
services:
  xui:
    build:
      context: .
      dockerfile: Dockerfile
    image: enwaiax/x-ui
    container_name: xui
    restart: unless-stopped
    network_mode: host
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
